-- ACHADEX - banco Supabase
-- Execute este arquivo no SQL Editor do seu projeto Supabase.

create extension if not exists "pgcrypto";

create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  name text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text,
  price numeric(12,2) not null default 0,
  image_url text,
  affiliate_url text not null,
  category text,
  published boolean not null default true,
  is_featured boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.clicks (
  id bigint generated by default as identity primary key,
  product_id uuid not null references public.products(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.products enable row level security;
alter table public.categories enable row level security;
alter table public.clicks enable row level security;

drop policy if exists "public can read published products" on public.products;
create policy "public can read published products"
on public.products for select
to anon, authenticated
using (published = true);

drop policy if exists "authenticated can read all products" on public.products;
create policy "authenticated can read all products"
on public.products for select
to authenticated
using (true);

drop policy if exists "authenticated can insert products" on public.products;
create policy "authenticated can insert products"
on public.products for insert
to authenticated
with check (true);

drop policy if exists "authenticated can update products" on public.products;
create policy "authenticated can update products"
on public.products for update
to authenticated
using (true)
with check (true);

drop policy if exists "authenticated can delete products" on public.products;
create policy "authenticated can delete products"
on public.products for delete
to authenticated
using (true);

drop policy if exists "public can read categories" on public.categories;
create policy "public can read categories"
on public.categories for select
to anon, authenticated
using (true);

drop policy if exists "authenticated can manage categories" on public.categories;
create policy "authenticated can manage categories"
on public.categories for all
to authenticated
using (true)
with check (true);

drop policy if exists "public can insert clicks" on public.clicks;
create policy "public can insert clicks"
on public.clicks for insert
to anon, authenticated
with check (true);

drop policy if exists "authenticated can read clicks" on public.clicks;
create policy "authenticated can read clicks"
on public.clicks for select
to authenticated
using (true);

insert into public.categories (name)
values ('Casa'), ('Eletrônicos'), ('Beleza'), ('Moda')
on conflict (name) do nothing;

-- Crie o usuário administrador em:
-- Supabase Dashboard > Authentication > Users > Add user
-- Depois use o e-mail e senha criados para entrar em /painel.

-- IMPORTANTE:
-- O frontend usa apenas a chave ANON/PUBLIC.
-- Nunca coloque a service_role key no .env do frontend.